version: "3"
services:
  web:
    image: httpd:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4040:80"
    networks:
      - webnet
networks:
  webnet:
