# Mongo
version: "3"

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - net
    volumes:
      - 'config:/data/configdb'
      - 'data:/data/db'
  ui:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "3838:8081"
    networks:
      - net

networks:
  net:

volumes:
  config:
  data:
