version: '3.3'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - cadvisor
    configs:
      - source: prometheus_yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - 'data:/prometheus'  
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  grafana:
    image: grafana/grafana
    environment:
      GF_SERVER_ROOT_URL: http://latitude.local
      GF_SECURITY_ADMIN_PASSWORD: secret
    ports:
      - 3030:3000
    depends_on:
    - prometheus     
    volumes:
      - 'data_grafana:/var/lib/grafana'     
configs:
  prometheus_yml:
    external: true

volumes:
  data:
  data_grafana:

